[pytest]
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::PendingDeprecationWarning
    ignore::DeprecationWarning
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::RuntimeWarning
