sonar.host.url=https://sonarqube.rakshitr.co.in
sonar.projectKey=HeluCryptic
sonar.projectName=HeluCryptic
sonar.sources=.
sonar.exclusions=tests/**,**/.git/**,**/__pycache__/**,**/.venv/**,**/.pytest_cache/**,**/.ruff_cache/**,**/assets/**,**/theme/**,**/tracks/**,**/icon.png,**/icon.ico,**/build/**,**/dist/**,**/node_modules/**
sonar.tests=tests
sonar.python.version=3.11
sonar.token=sqp_67d40716826e047825d47e16616dd68f3af1c46f